package com.htxx.demo.model;

import java.util.HashSet;
import java.util.Set;


/**
 * AbstractDepartment generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractDepartment  implements java.io.Serializable {


    // Fields    

     private String departmentId;
     private String departmentName;
     private Set employees = new HashSet(0);


    // Constructors

    /** default constructor */
    public AbstractDepartment() {
    }
    
    public AbstractDepartment(String departmentName){
    	this.departmentName = departmentName;
    }

    
    /** full constructor */
    public AbstractDepartment(String departmentName, Set employees) {
        this.departmentName = departmentName;
        this.employees = employees;
    }

   
    // Property accessors

    public String getDepartmentId() {
        return this.departmentId;
    }
    
    public void setDepartmentId(String departmentId) {
        this.departmentId = departmentId;
    }

    public String getDepartmentName() {
        return this.departmentName;
    }
    
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }

    public Set getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Set employees) {
        this.employees = employees;
    }
}