package com.htxx.demo.model;


import java.util.Set;


/**
 * Department generated by MyEclipse - Hibernate Tools
 */
public class Department extends AbstractDepartment implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public Department() {
    }

    /** minimal constructor */
    public Department(String departmentName){
    	super(departmentName);
    }
    /** full constructor */
    public Department(String departmentName, Set employees) {
        super(departmentName, employees);        
    }
   
}
