(function(){var f=true,g=null,j=false,k=this,aa=function(a,b,c){a=a.split(".");c=c||k;!(a[0]in c)&&c.execScript&&c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)if(!a.length&&b!==undefined)c[d]=b;else c=c[d]?c[d]:c[d]={}},ba=function(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array||!(a instanceof Object)&&Object.prototype.toString.call(a)=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";
if(!(a instanceof Object)&&(Object.prototype.toString.call(a)=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call")))return"function"}else return"null";else if(b=="function"&&typeof a.call=="undefined")return"object";return b};Math.floor(Math.random()*2147483648).toString(36);
var ca=function(a,b){var c=b||k;if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(c,e)}}else return function(){return a.apply(c,arguments)}},m=function(a,b,c){aa(a,b,c)},da=function(a,b,c){a[b]=c},o=function(a,b){function c(){}c.prototype=b.prototype;a.Ba=b.prototype;a.prototype=new c};var p=function(a,b){var c=parseFloat(a);return isNaN(c)||c>1||c<0?b:c},fa=function(a,b){if(a=="true")return f;if(a=="false")return j;return b},ga=/^([\w-]+\.)*([\w-]{2,})(\:[0-9]+)?$/,q=function(a,b){if(!a)return b;var c=a.match(ga);return c?c[0]:b};var ha=function(){return q("","pagead2.googlesyndication.com")};var ka=function(a){if(a.indexOf("&")!=-1)return"document"in k&&a.indexOf("<")==-1?ia(a):ja(a);return a},ia=function(a){var b=k.document.createElement("a");b.innerHTML=a;b.normalize&&b.normalize();a=b.firstChild.nodeValue;b.innerHTML="";return a},ja=function(a){return a.replace(/&([^;]+);/g,function(b,c){switch(c){case "amp":return"&";case "lt":return"<";case "gt":return">";case "quot":return'"';default:if(c.charAt(0)=="#"){var d=Number("0"+c.substr(1));if(!isNaN(d))return String.fromCharCode(d)}return b}})},
ma=function(a,b){for(var c=0,d=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),e=String(b).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),h=Math.max(d.length,e.length),i=0;c==0&&i<h;i++){var l=d[i]||"",n=e[i]||"",G=RegExp("(\\d*)(\\D*)","g"),z=RegExp("(\\d*)(\\D*)","g");do{var A=G.exec(l)||["","",""],B=z.exec(n)||["","",""];if(A[0].length==0&&B[0].length==0)break;c=A[1].length==0?0:parseInt(A[1],10);var ea=B[1].length==0?0:parseInt(B[1],10);c=la(c,ea)||la(A[2].length==0,B[2].length==0)||
la(A[2],B[2])}while(c==0)}return c},la=function(a,b){if(a<b)return-1;else if(a>b)return 1;return 0};var r=function(a,b){this.width=a;this.height=b};r.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};r.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};var s,na,oa,pa,qa,ra,sa,ta,ua,va=function(){return k.navigator?k.navigator.userAgent:g},wa=function(){return k.navigator},xa=function(){qa=pa=oa=na=s=j;var a;if(a=va()){var b=wa();s=a.indexOf("Opera")==0;na=!s&&a.indexOf("MSIE")!=-1;pa=(oa=!s&&a.indexOf("WebKit")!=-1)&&a.indexOf("Mobile")!=-1;qa=!s&&!oa&&b.product=="Gecko"}};xa();
var ya=s,za=na,Aa=qa,Ba=oa,Ca=pa,Da=function(){var a=wa();return a&&a.platform||""},Ea=Da(),Fa=function(){ra=Ea.indexOf("Mac")!=-1;sa=Ea.indexOf("Win")!=-1;ta=Ea.indexOf("Linux")!=-1;ua=!!wa()&&(wa().appVersion||"").indexOf("X11")!=-1};Fa();var Ga=function(){var a="",b;if(ya&&k.opera){a=k.opera.version;a=typeof a=="function"?a():a}else{if(Aa)b=/rv\:([^\);]+)(\)|;)/;else if(za)b=/MSIE\s+([^\);]+)(\)|;)/;else if(Ba)b=/WebKit\/(\S+)/;if(b)a=(a=b.exec(va()))?a[1]:""}return a},Ha=Ga(),Ia={};var Ja=function(a){var b=a.document;if(Ba&&!(Ia["500"]||(Ia["500"]=ma(Ha,"500")>=0))&&!Ca){if(typeof a.innerHeight=="undefined")a=window;b=a.innerHeight;var c=a.document.documentElement.scrollHeight;if(a==a.top)if(c<b)b-=15;return new r(a.innerWidth,b)}a=b.compatMode=="CSS1Compat";if(ya&&!(Ia["9.50"]||(Ia["9.50"]=ma(Ha,"9.50")>=0)))a=j;a=a?b.documentElement:b.body;return new r(a.clientWidth,a.clientHeight)};var t=document,u=window,Ka=function(a){var b=g;if((a=a.getElementsByTagName("script"))&&a.length){b=a[a.length-1];b=b.parentNode}return b};Ka(t);var La="http://"+ha()+"/pagead/show_ads.js";function v(a){return typeof encodeURIComponent=="function"?encodeURIComponent(a):escape(a)}function Ma(a,b,c){var d=document.createElement("script");d.type="text/javascript";if(b)d.onload=b;if(c)d.id=c;d.src=a;var e=document.getElementsByTagName("head")[0];if(!e)return j;window.setTimeout(function(){e.appendChild(d)},0);return f}
function Na(a,b){if(a.attachEvent){a.attachEvent("onload",b);return f}if(a.addEventListener){a.addEventListener("load",b,j);return f}return j}var Oa=function(a){if(!("google_onload_fired"in a)){a.google_onload_fired=j;Na(a,function(){a.google_onload_fired=f})}};function Pa(a,b){a.google_image_requests||(a.google_image_requests=[]);var c=new Image;c.src=b;a.google_image_requests.push(c)}function w(a){if(a in Qa)return Qa[a];return Qa[a]=navigator.userAgent.toLowerCase().indexOf(a)!=-1}var Qa={};
function Ra(){return w("msie")&&!window.opera}
function Sa(){if(navigator.plugins&&navigator.mimeTypes.length){var a=navigator.plugins["Shockwave Flash"];if(a&&a.description)return a.description.replace(/([a-zA-Z]|\s)+/,"").replace(/(\s)+r/,".")}else if(navigator.userAgent&&navigator.userAgent.indexOf("Windows CE")>=0){a=3;for(var b=1;b;)try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+(a+1));a++}catch(c){b=g}return a.toString()}else if(Ra()){b=g;try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7")}catch(d){a=0;try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");
a=6;b.AllowScriptAccess="always"}catch(e){if(a==6)return a.toString()}try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(h){}}if(b){a=b.GetVariable("$version").split(" ")[1];return a.replace(/,/g,".")}}return"0"}function Ta(a,b){if(!(Math.random()<1.0E-4)){var c=Math.random();if(c<b){c=Math.floor(c/b*a.length);return a[c]}}return""}
var Ua=function(a){a.u_tz=-(new Date).getTimezoneOffset();a.u_his=window.history.length;a.u_java=navigator.javaEnabled();if(window.screen){a.u_h=window.screen.height;a.u_w=window.screen.width;a.u_ah=window.screen.availHeight;a.u_aw=window.screen.availWidth;a.u_cd=window.screen.colorDepth}if(navigator.plugins)a.u_nplug=navigator.plugins.length;if(navigator.mimeTypes)a.u_nmime=navigator.mimeTypes.length},Va=function(a,b){var c=b||u;if(a&&c.top!=c)c=c.top;try{return c.document&&!c.document.body?new r(-1,
-1):Ja(c||window)}catch(d){return new r(-12245933,-12245933)}},Wa=function(a,b){var c=a.length;if(c==0)return 0;for(var d=b||305419896,e=0;e<c;e++){var h=a.charCodeAt(e);d^=(d<<5)+(d>>2)+h&4294967295}return d>0?d:4294967296+d},Xa=function(a){if(a==a.top)return 0;var b=[];b.push(a.document.URL);a.name&&b.push(a.name);var c=f;a=Va(!c,a);b.push(a.width.toString());b.push(a.height.toString());return Wa(b.join(""))},Ya=function(a){if(!a)return"";var b=[],c=0;for(a=a;a&&c<25;a=a.parentNode,++c)b.push(a.id||
"");return b.join()},Za=function(a){try{return!!a.document}catch(b){return j}};var $a=p("0.005",0),ab=p("0.01",0),bb=p("0.001",0),cb=p("0.006",0),db=p("0.008",0);var eb=fa("false",j),fb=fa("false",j),gb=fa("false",j),hb=fa("false",j);var ib=function(a,b,c){b=ca(b,k,a);a=window.onerror;window.onerror=b;try{c()}catch(d){c=d.toString();var e="";if(d.fileName)e=d.fileName;var h=-1;if(d.lineNumber)h=d.lineNumber;b=b(c,e,h);if(!b)throw d;}window.onerror=a};m("google_protectAndRun",ib);
var kb=function(a,b,c,d){if(Math.random()<0.01){var e=t;a=["http://",q("","pagead2.googlesyndication.com"),"/pagead/gen_204","?id=jserror","&jscb=",eb?1:0,"&jscd=",fb?1:0,"&context=",v(a),"&msg=",v(b),"&file=",v(c),"&line=",v(d.toString()),"&url=",v(e.URL.substring(0,512)),"&ref=",v(e.referrer.substring(0,512))];a.push(jb());Pa(u,a.join(""))}return!gb};m("google_handleError",kb);
var jb=function(){var a=["&client=",v(u.google_ad_client),"&format=",v(u.google_ad_format),"&slotname=",v(u.google_ad_slot),"&output=",v(u.google_ad_output),"&ad_type=",v(u.google_ad_type)];return a.join("")};var x=function(){this.Z=[];this.qa=window;this.v=0},lb=function(a,b){this.fn=a;this.win=b};x.prototype.enqueue=function(a,b){this.Z.push(new lb(a,b||this.qa));mb(this)};x.prototype.Y=function(){this.v=1};x.prototype.$=function(){if(this.v==1)this.v=0;mb(this)};da(x.prototype,"nq",x.prototype.enqueue);da(x.prototype,"al",x.prototype.Y);da(x.prototype,"rl",x.prototype.$);var mb=function(a){a.qa.setTimeout(ca(a.pa,a),0)};
x.prototype.pa=function(){if(this.v==0&&this.Z.length){var a=this.Z.shift();this.v=2;a.win.setTimeout(ca(this.na,this,a),0);mb(this)}};x.prototype.na=function(a){this.v=0;a.fn()};var nb,ob,pb,qb,rb,sb,tb,ub=function(){tb=sb=rb=qb=pb=ob=nb=j;var a=va();if(a)if(a.indexOf("Firefox")!=-1)nb=f;else if(a.indexOf("Camino")!=-1)ob=f;else if(a.indexOf("iPhone")!=-1||a.indexOf("iPod")!=-1)pb=f;else if(a.indexOf("iPad")!=-1)qb=f;else if(a.indexOf("Android")!=-1)rb=f;else if(a.indexOf("Chrome")!=-1)sb=f;else if(a.indexOf("Safari")!=-1)tb=f};ub();var vb=!!window.google_async_iframe_id,y=vb&&window.parent||window,wb=function(){if(vb&&!Za(y)){for(var a="."+t.domain;a.split(".").length>2&&!Za(y);){t.domain=a=a.substr(a.indexOf(".")+1);y=window.parent}Za(y)||(y=window)}return y};var C=function(a){this.C=a;this.W=[];this.V=0;this.I=[];this.ia=0;this.O=[];this.ha=j;this.f=this.ea="";this.ga=j},xb=function(a,b,c){var d=a.C[c],e=a.W;a.C[c]=function(h){if(h&&h.length>0){var i=h.length>1?h[1].url:g;e.push([b,ka(h[0].url),i])}d(h)}},yb=function(a){a.V++},zb=function(a,b){a.I.push(b)},Ab="http://"+ha()+"/pagead/osd.js",Bb=function(a){if(!a.ha){Oa(wb());Ma(Ab);a.ha=f}},Cb=function(a,b){if(a.V>0)for(var c=a.C.document.getElementsByTagName("iframe"),d=a.ga?"google_ads_iframe_":"google_ads_frame",
e=0;e<c.length;e++){var h=c.item(e);h.src&&h.name&&h.name.indexOf(d)==0&&b(h,h.src)}},Db=function(a,b){var c=a.W;if(c.length>0)for(var d=a.C.document.getElementsByTagName("a"),e=0;e<d.length;e++)for(var h=0;h<c.length;h++)if(d.item(e).href==c[h][1]){var i=d.item(e).parentNode;if(c[h][2])for(var l=i,n=0;n<4;n++){if(l.innerHTML.indexOf(c[h][2])>0){i=l;break}l=l.parentNode}b(i,c[h][0]);c.splice(h,1);break}},Fb=function(a,b){for(var c=0;c<a.I.length;c++){var d=a.I[c],e=Eb(d);if(e)(e=a.C.document.getElementById("google_ads_div_"+
e))&&b(e,d)}};C.prototype.T=function(a){Db(this,a);Fb(this,a);Cb(this,a)};C.prototype.setupOsd=function(a,b,c){this.ia=a;this.ea=b;this.f=c};C.prototype.getOsdMode=function(){return this.ia};C.prototype.getEid=function(){return this.ea};C.prototype.getCorrelator=function(){return this.f};C.prototype.U=function(){return this.W.length+this.V+this.I.length};C.prototype.setValidOutputTypes=function(a){this.O=a};
C.prototype.registerAdBlockByType=function(a,b,c){if(this.O.length>0){for(var d=0;d<this.O.length;d++)if(this.O[d]==a){this.ga=c;if(a=="js")xb(this,b,"google_ad_request_done");else if(a=="html")yb(this);else a=="json_html"&&zb(this,b)}Bb(this)}};var Eb=function(a){if((a=a.match(/[&\?](?:slotname)=([^&]+)/))&&a.length==2)return a[1];return""},Gb=function(){var a=wb();a.__google_ad_urls||(a.__google_ad_urls=new C(a));return a.__google_ad_urls};m("Goog_AdSense_getAdAdapterInstance",Gb);
m("Goog_AdSense_OsdAdapter",C);m("Goog_AdSense_OsdAdapter.prototype.numBlocks",C.prototype.U);m("Goog_AdSense_OsdAdapter.prototype.findBlocks",C.prototype.T);m("Goog_AdSense_OsdAdapter.prototype.getOsdMode",C.prototype.getOsdMode);m("Goog_AdSense_OsdAdapter.prototype.getEid",C.prototype.getEid);m("Goog_AdSense_OsdAdapter.prototype.getCorrelator",C.prototype.getCorrelator);m("Goog_AdSense_OsdAdapter.prototype.setValidOutputTypes",C.prototype.setValidOutputTypes);
m("Goog_AdSense_OsdAdapter.prototype.setupOsd",C.prototype.setupOsd);m("Goog_AdSense_OsdAdapter.prototype.registerAdBlockByType",C.prototype.registerAdBlockByType);var Hb={google_ad_channel:"channel",google_ad_host:"host",google_ad_host_channel:"h_ch",google_ad_host_tier_id:"ht_id",google_ad_section:"region",google_ad_type:"ad_type",google_adtest:"adtest",google_allow_expandable_ads:"ea",google_alternate_ad_url:"alternate_ad_url",google_alternate_color:"alt_color",google_bid:"bid",google_city:"gcs",google_color_bg:"color_bg",google_color_border:"color_border",google_color_line:"color_line",google_color_link:"color_link",google_color_text:"color_text",google_color_url:"color_url",
google_contents:"contents",google_country:"gl",google_cpm:"cpm",google_cust_age:"cust_age",google_cust_ch:"cust_ch",google_cust_gender:"cust_gender",google_cust_id:"cust_id",google_cust_interests:"cust_interests",google_cust_job:"cust_job",google_cust_l:"cust_l",google_cust_lh:"cust_lh",google_cust_u_url:"cust_u_url",google_disable_video_autoplay:"disable_video_autoplay",google_ed:"ed",google_encoding:"oe",google_feedback:"feedback_link",google_flash_version:"flash",google_font_face:"f",google_font_size:"fs",
google_hints:"hints",google_kw:"kw",google_kw_type:"kw_type",google_language:"hl",google_page_url:"url",google_region:"gr",google_reuse_colors:"reuse_colors",google_safe:"adsafe",google_tag_info:"gut",google_targeting:"targeting",google_targeting_video_doc_id:"tvdi",google_ui_features:"ui",google_ui_version:"uiv",google_video_doc_id:"video_doc_id",google_video_product_type:"video_product_type"},Ib={google_ad_block:"ad_block",google_ad_client:"client",google_ad_format:"format",google_ad_output:"output",
google_ad_callback:"callback",google_ad_height:"h",google_ad_override:"google_ad_override",google_ad_slot:"slotname",google_ad_width:"w",google_ctr_threshold:"ctr_t",google_image_size:"image_size",google_last_modified_time:"lmt",google_max_num_ads:"num_ads",google_max_radlink_len:"max_radlink_len",google_num_radlinks:"num_radlinks",google_num_radlinks_per_unit:"num_radlinks_per_unit",google_only_ads_with_video:"only_ads_with_video",google_rl_dest_url:"rl_dest_url",google_rl_filtering:"rl_filtering",
google_rl_mode:"rl_mode",google_rt:"rt",google_skip:"skip"},Jb={google_only_pyv_ads:"pyv",google_with_pyv_ads:"withpyv"};var D=document,E=navigator,F=window;
function Kb(){var a=D.cookie,b=Math.round((new Date).getTime()/1E3),c=F.google_analytics_domain_name;c=typeof c=="undefined"?Lb("auto"):Lb(c);var d=a.indexOf("__utma="+c+".")>-1,e=a.indexOf("__utmb="+c)>-1,h=a.indexOf("__utmc="+c)>-1,i={},l=!!F&&!!F.gaGlobal;if(d){a=a.split("__utma="+c+".")[1].split(";")[0].split(".");i.sid=e&&h?a[3]+"":l&&F.gaGlobal.sid?F.gaGlobal.sid:b+"";i.vid=a[0]+"."+a[1];i.from_cookie=f}else{i.sid=l&&F.gaGlobal.sid?F.gaGlobal.sid:b+"";i.vid=l&&F.gaGlobal.vid?F.gaGlobal.vid:
(Math.round(Math.random()*2147483647)^Mb()&2147483647)+"."+b;i.from_cookie=j}i.dh=c;i.hid=l&&F.gaGlobal.hid?F.gaGlobal.hid:Math.round(Math.random()*2147483647);return F.gaGlobal=i}
function Mb(){var a=D.cookie?D.cookie:"",b=F.history.length,c,d=[E.appName,E.version,E.language?E.language:E.browserLanguage,E.platform,E.userAgent,E.javaEnabled()?1:0].join("");if(F.screen)d+=F.screen.width+"x"+F.screen.height+F.screen.colorDepth;else if(F.java){c=java.awt.Toolkit.getDefaultToolkit().getScreenSize();d+=c.screen.width+"x"+c.screen.height}d+=a;d+=D.referrer?D.referrer:"";for(a=d.length;b>0;)d+=b--^a++;return Nb(d)}
function Nb(a){var b=1,c=0,d;if(!(a==undefined||a=="")){b=0;for(d=a.length-1;d>=0;d--){c=a.charCodeAt(d);b=(b<<6&268435455)+c+(c<<14);c=b&266338304;b=c!=0?b^c>>21:b}}return b}function Lb(a){if(!a||a==""||a=="none")return 1;if("auto"==a){a=D.domain;if("www."==a.substring(0,4))a=a.substring(4,a.length)}return Nb(a.toLowerCase())};function Ob(a,b,c,d){this._value_=a;this._expires_=b;this._path_=c;this._domain_=d;if(!this._path_)this._path_="/";if(this._domain_==g)this._domain_=document.domain}Ob.prototype.toString=function(){return"[GA_GoogleCookieInfo: value="+this._value_+", expires="+this._expires_+", path="+this._path_+"]"};function H(){this.w=Pb(this);this.Q=j;if(!this.w)this.Q=Qb(this)}H.prototype.P="__gads=";H.prototype.D="GoogleAdServingTest=";H.prototype.M=function(a){this.q=a._cookies_[0];if(this.q!=g){this.w=this.q._value_;Rb(this)}};da(H.prototype,"setCookieInfo",H.prototype.M);
var Sb=function(a,b){var c=(new Date).valueOf(),d=new Date;d.setTime(c+b);return d},Tb=function(a){var b=15552E6;a=Sb(a,b);b="ID=12345:T="+b;var c="/",d=document.domain;return new Ob(b,a.valueOf(),c,d)},Ub="http://"+q("","partner.googleadservices.com")+"/gampad/cookie.js?callback=_GA_googleCookieHelper.setCookieInfo",Vb=function(a,b){if(!(a.w||!a.Q)){var c="script",d=document.domain;d=Ub+"&client="+v(b)+"&domain="+v(d);document.write("<"+c+' src="'+d+'"></'+c+">")}},Qb=function(a){document.cookie=
a.D+"Good";var b=Wb(a,a.D);if(b=b=="Good"){var c=Sb(a,-1);document.cookie=a.D+"; expires="+c.toGMTString()}return b},Pb=function(a){return a=Wb(a,a.P)},Wb=function(a,b){var c=document.cookie,d=c.indexOf(b),e="";if(d!=-1){d=d+b.length;e=c.indexOf(";",d);if(e==-1)e=c.length;e=c.substring(d,e)}return e},Rb=function(a){if(a.q!=g)if(a.w){var b=new Date;b.setTime(1E3*a.q._expires_);var c=a.q._domain_;a=a.P+a.w+"; expires="+b.toGMTString()+"; path="+a.q._path_+"; domain=."+c;document.cookie=a}};function Xb(a,b){try{return a.top.document==b}catch(c){}return j};var Yb=function(a){var b="google_unique_id";if(a[b])++a[b];else a[b]=1;return a[b]};var Zb=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^/?#]*)@)?([\\w\\d\\-\\u0100-\\uffff.%]*)(?::([0-9]+))?)?([^?#]+)?(?:\\?([^#]*))?(?:#(.*))?$"),$b=function(a){return a&&decodeURIComponent(a)};var ac=function(a){this.oa=(this.R=a&&a.GA_jstiming)&&this.R.load};ac.prototype.tick=function(a,b){this.oa.tick(a,b)};ac.prototype.report=function(a){var b={};b.e=a;this.R.report(this.oa,b)};var bc=function(){};o(bc,ac);bc.prototype.tick=function(){};bc.prototype.report=function(){};var cc=function(a,b,c,d){if(c<=4){b=b+"_"+c;d?a.tick(b,d+"_"+c):a.tick(b)}};var dc=function(a,b){var c=0,d=[];a&&d.push(a);if(b){var e=Ya(b);e&&d.push(e)}if(d.length>0)c=Wa(d.join(":"));return c.toString()};var I=u&&Math.random()<$a&&u.GA_jstiming&&u.GA_jstiming.load&&u.location.protocol=="http:"?new ac(u):new bc(u);I.tick("js_load");function J(a){return typeof a=="function"}function ec(a,b){if(typeof a!="string"||a.length==0)return g;else if(typeof b!="string"||b.length==0)return g;return fc(K(),a,b)}m("GA_googleAddSlot",ec);function _GA_googleInitializeAdEngine(a){if(!L()){gc(hc(a));ic(L())}}m("_GA_googleInitializeAdEngine",_GA_googleInitializeAdEngine);
function jc(){K().ra=f;_GA_googleInitializeAdEngine(g);var a=L().g;a=="sync"||a=="sync_sra"?L().j():kc(K())}m("GA_googleFetchAds",jc);function lc(){_GA_googleInitializeAdEngine("iframe");Vb(window._GA_googleCookieHelper,window.GS_googleGetIdsForAdSenseService())}m("GA_googleUseIframeRendering",lc);function mc(){var a=window.GA_googleEnv.getParameter("google_ad_impl");a==g&&window.GA_googleEnv.setParameter("google_ad_impl","sync_sra")}m("GA_googleUseSyncSRARendering",mc);
function nc(a){window.GA_googleEnv.setParameter("google_domain_reset_url",a)}m("GA_googleDomainResetUrl",nc);function oc(a){var b=Ka(t);pc(K(),a,b);if(L()!=g)if(L().g!="iframe"){if(qc(L()))if(L().N){b=M(K(),a);if(b==g)return;else if(!b._enabled_)return}else return;else if(N(L(),a)!=g&&!L().l)return;L().n(a)}}m("GA_googleFillSlot",oc);function rc(a,b,c,d){a=a||"";b=b||"";c=c||0;d=d||0;var e=Ka(t);pc(K(),b,e);if(L()!=g)if(L().g=="iframe"){fc(K(),a,b);a=new sc(c,d,j,f);tc(K(),b,a);L().n(b)}}
m("GA_googleFillSlotWithSize",rc);function uc(){vc(new wc(Hb));gc(g)}m("GA_googleResetAll",uc);window.google_noFetch=j;function xc(){window.google_noFetch=f}m("GA_googleNoFetch",xc);function yc(){window.google_delayFetch=f}m("GA_googleDelayFetch",yc);function sc(a,b,c,d){this._width_=a;this._height_=b;this._expandable_=c;this._enabled_=d}
sc.prototype.toString=function(){return"[GA_GoogleAdSlotAttr: width="+this._width_+", height="+this._height_+", expandable="+this._expandable_+", enabled="+this._enabled_+"]"};function zc(a){var b={};a=a.split("?");a=a[a.length-1].split("&");for(var c=0;c<a.length;c++){var d=a[c].split("=");if(d[0])try{b[d[0].toLowerCase()]=d.length>1?window.decodeURIComponent?decodeURIComponent(d[1].replace(Ac," ")):unescape(d[1]):""}catch(e){}}return b}function Bc(a){a=a||document.URL;this.la=zc(a)}
Bc.prototype.getParameter=function(a){return a==g?g:this.la[a]};Bc.prototype.setParameter=function(a,b){this.la[a]=b};var Cc=function(){if(!hb)return"http://"+q("","pubads.g.doubleclick.net");return"https://"+q("","securepubads.g.doubleclick.net")};function O(a){return a.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;")}function Dc(){this.G=g;this.ma=j;this.Aa=(new Date).valueOf()}
var Fc=function(a,b){if(a.G==g)if(!a.ma){a.G=window.open("","GoogleAdCapture","width=1100, height=1400, status=no, resizable=yes, scrollbars=yes,menubar=yes, toolbar=yes");if(a.G){var c=a.G.document,d=[];d.push('<html>\n<head>\n<title>Google Ad Capture Window</title>\n<script>function displayTime(id, start){var delta=(new Date()).valueOf() - start;document.getElementById(id).innerHTML=""+delta;}var pageStartTime = (new Date()).valueOf();var slotStartTime = 0;window.onload=function(){displayTime("total", pageStartTime);};<\/script></head>\n<body>\n');
d.push("<p>Google Ad Capture Window</p>");for(var e in b)J(b[e])||d.push(Ec(a,e,b[e]));d.push("<p>Time blocked rendering ads (ms): <label id='blocked'></label>");d.push("<script>displayTime('blocked', pageStartTime);<\/script>");d.push("<p>Total Page Load Time (ms): <label id='total'></label>");d.push("</body>\n</html>");d=d.join("\n");(e=window.GA_googleEnv.getParameter("google_capture_norender")!=g)?c.write(O(d)):c.write(d);c.close()}else a.ma=f}},Ec=function(a,b,c){a="<script>slotStartTime = (new Date()).valueOf();<\/script>";
var d="<p>Slot "+b+"</p>";c=c==g||c._html_==g?"No ad":c._html_;var e="<p>Slot Time (ms): <label id='"+b+"'></label>";b='<script>displayTime("'+b+'", slotStartTime);<\/script>';return a+d+"\n"+c+"\n"+e+b};function Gc(a){this.d={};this.F=a}var Hc=function(a,b,c,d){if(b){c||(c="");if(b=="google_gl")b="google_country";else if(b=="google_region")b="google_section";if(b in a.F)if((d=typeof d=="undefined"||d)||!a.d[b])a.d[b]=c}},Ic=function(a,b){for(var c in b.d)J(b.d[c])||a.d[c]||(a.d[c]=b.d[c])};
Gc.prototype.getAttribute=function(a){return this.d[a]};Gc.prototype.i=function(){var a=[];for(var b in this.d)if(!J(this.d[b])){var c=Hb[b]||Ib[b]||Jb[b]||g,d=this.d[b];c&&d&&a.push(c+"="+v(d))}return a.join("&")};
var Kc=function(a,b,c,d){a=Jc(a,b,c,d);b=[];a[0]&&a[0].length>0&&b.push(a[0].join("&"));a[1]&&a[1].length>0&&b.push("sps="+a[1].join("|"));return b.join("&")},Jc=function(a,b,c,d){var e=[],h=[];b=b.d;for(var i in d)if(!J(i)){var l=d[i];if(l){var n="";if(b[i]!=g)n=v(b[i]);var G=[],z=-1,A=-1;for(var B in a)if(!J(a[B])){++z;if(c[B]==g)G.push("");else{var ea=c[B].d;if(ea[i]!=g){G.push(v(v(ea[i])));A=z}else G.push("")}}if(A>=0){z=v(n);n=[];n.push(z);for(z=0;z<=A;++z)n.push(G[z]);h.push(l+","+n.join(","))}else n&&
e.push(l+"="+n)}}a=[];a.push(e);a.push(h);return a};function Lc(a,b){this.L=a;this.s=b;this.aa=0;this.xa=this.S=this.X=j;this.va=this.wa=this.fa=this.sa=g}var Mc=function(a){a.S=f;a.sa=(new Date).valueOf()},Nc=function(a){a.fa=(new Date).valueOf()},Oc=function(a){a.xa=f;a.wa=(new Date).valueOf()},Pc=function(a){a.va=(new Date).valueOf()};Lc.prototype.toString=function(){return"[GA_GoogleAdSlot: pubid="+this.L+", name="+this.s+", loaded="+this.X+", tries="+this.aa+"]"};
function wc(a){this.a={};this.c=[];this.r={};this.F=a;this.ka=new Gc(this.F);this.B={};this.ra=j;this.o=g;this.ca={}}
var fc=function(a,b,c){b=new Lc(b,c);return a.a[b.s]=b},Qc=function(a,b){var c=[];for(var d in a.a)if(!J(a.a[d])){if(b){var e=M(a,d);if(e==g||!e._enabled_)continue}e=a.a[d];e.S||c.push(e)}return c},Rc=function(a,b){return Qc(a,b).length},Sc=function(a){var b=[];for(var c in a.a){var d=a.a[c];J(d)||d.S&&d.fa==g&&b.push(c)}return b},Tc=function(a){var b=0;for(var c in a.a)if(!J(a.a[c])){var d=M(a,c);d!=g&&d._enabled_&&b++}return b},Uc=function(a){for(var b in a.a)if(!J(a.a[b])){var c=a.a[b];Mc(c)}},
Vc=function(a,b){var c=a.a[b];Mc(c)},Wc=function(a,b){var c=a.a[b];Nc(c)},Xc=function(a,b){var c=a.a[b];Oc(c)},P=function(a,b){var c=a.a[b];Pc(c);cc(I,"ga_render",a.c.length,"ga_srt")},Yc=function(a){var b=0;for(var c in a.a)J(a.a[c])||b++;return b};wc.prototype.toString=function(){var a="[AdData:",b=[];for(var c in this.a)J(this.a[c])||b.push(this.a[c].toString());for(var d in this.r)J(this.r[d])||b.push("["+d+","+this.r[d]+"]");a+=b.join();a+="]";return a};
var Q=function(a,b){return a.a[b]},Zc=function(a,b,c){if(!(b==g||b.length==0)){if(c==g||c.length==0)c="";var d=a.r[b];a.r[b]=d==g?c:d+","+c}};function $c(a,b){Zc(K(),a,b)}m("GA_googleAddAttr",$c);var ad=function(a,b,c){Hc(a.ka,b,c)};function bd(a,b){ad(K(),a,b)}m("GA_googleAddAdSensePageAttr",bd);var cd=function(a){return a.ka},dd=function(a,b,c,d){if(!(b==g||b.length==0)){if(L()==g||L().g!="iframe"){var e=a.a[b];if(e==g)return}e=a.B[b];if(e==g)a.B[b]=new Gc(a.F);Hc(a.B[b],c,d)}};
function ed(a,b,c){dd(K(),a,b,c)}m("GA_googleAddAdSenseSlotAttr",ed);
var fd=function(a,b){return a.B[b]},pc=function(a,b,c){a.ca[b]=c},gd=function(a,b){return a.ca[b]},hd=function(){var a=Cc();return a+"/gampad/slotdata.js?callback=GA_googleSetAdSlotAttributes"},kc=function(a){if(a.o!=g)L().j();else{var b=[];for(var c in a.a)J(a.a[c])||b.push(c);a=window.GS_googleGetIdsForAdSenseService();b=hd(window)+"&client="+escape(a)+"&page_slots="+escape(b.join());document.write("<script src = '"+b+"'><\/script>")}},id=function(a,b){a.o=b;L().N=f;L().j()};
function jd(a){id(K(),a)}m("GA_googleSetAdSlotAttributes",jd);var tc=function(a,b,c){if(a.o==g)a.o={};a.o[b]=c;L().N=f},M=function(a,b){return a.o!=g?a.o[b]:g};function kd(a,b,c){if(!c||c<0||c>1)c=0;this.ya=Math.random()<c;this.ta=a;this.ba=b+"/pagead/gen_204?id="+v(a);this.ua=[]}
var R=function(a,b,c){if(b&&b.match(/^\w+$/)&&c)a.ba+="&"+b+"="+v(c)},ld=function(a){var b=K();for(var c in b.a){var d=b.a[c];if(!J(d)&&d.L!=g){R(a,"pub_id",d.L);break}}R(a,"nslots",Yc(b).toString());R(a,"pub_url",document.URL);R(a,"pub_ref",document.referrer)},md=function(a){if(!a.ya||!a.ta||!a.ba)return j;var b=new Image;b.src=a.ba;a.ua.push(b);return f};function S(a){this.h=g;this.o={};this.p=this.b="";this.l=a;this.m=this.K=this.t=j;this.g="sync";this.za=Hb;this.u=f;this.da=this.N=j}
var ic=function(a){a.t=window.GA_googleEnv.getParameter("google_nofetch")!=g||window.google_noFetch;a.K=window.GA_googleEnv.getParameter("google_norender")!=g;a.m=window.GA_googleEnv.getParameter("google_capture")!=g||window.GA_googleEnv.getParameter("google_capture_norender")!=g;if(a.m)a.K=f;nd(a,window);a.b=a.p;var b=ca(a.ja,a);od(a,window,b)},pd=function(a){a.da=f},od=function(a,b,c){if(b.attachEvent){b.attachEvent("onload",c);return f}if(b.addEventListener){b.addEventListener("load",c,j);return f}return j};
S.prototype.H=function(){this.m&&Fc(window.GA_googleAdCapture,this.h)};var qd=function(a){if(a.g=="sync_sra"){var b=K(),c=Yc(b);b=b.c.length;if(c!=b){a.J=new kd("sra_mismatch",Cc(),bb);R(a.J,"correlator",a.f);R(a.J,"fslots",b.toString());ld(a.J);md(a.J)}}},rd=function(a){I.tick("ga_onload");I.report(a.g)},sd=function(a){var b=Sc(K());if(b.length>0){a.A=new kd("missing_cb",Cc(),ab);R(a.A,"pending",b.join());R(a.A,"correlator",a.f);R(a.A,"impl",a.g);ld(a.A);md(a.A)}};
S.prototype.ja=function(){rd(this);this.H();qd(this);sd(this)};var nd=function(a){var b=window.GA_googleEnv.getParameter("google_ad_url");if(b==g||b.length==0)a.p=Cc()+"/gampad/ads?";else{if(b.charAt(b.length-1)!="?")b+="?";a.p=b}};S.prototype.k=function(){};
var N=function(a,b){return a.h!=g?a.h[b]:g},td=function(){var a=navigator.userAgent,b=a.indexOf("MSIE ");return b==-1?0:parseFloat(a.substring(b+5,a.indexOf(";",b)))},Ac=/\+/g,ud=function(a,b){b=b.toLowerCase();if(b.substring(0,3)!="ca-")b="ca-"+b;return b},U=function(a,b,c){c!=g&&T(a,b,v(c.toString()))},T=function(a,b,c){if(c!=g&&c!="")a.b+=a.b.charAt(a.b.length-1)!="?"?"&"+b+"="+c:b+"="+c},vd=function(a,b){for(var c=Qc(K(),a.u),d=[],e=[],h=[],i=c.length,l=0;l<i;l++){var n=c[l];h.push(n.s);if(!(b!=
g&&b!=n.s)){d.push(n.s);e.push(ud(a,n.L))}}U(a,"client",e[0]);if(a.l)h.length>0&&U(a,"page_slots",h.join());else{U(a,"slotname",d.join());K().c.length>0&&U(a,"page_slots",K().c.join())}},wd=function(a,b,c){if(c!=g){a=b.lastIndexOf("?");a=b.indexOf("google_preview=",a);c=b.indexOf("&",a);if(c==-1){c=b.length-1;a-=1}return b.substring(0,a)+b.substring(c+1,b.length)}return b},xd=function(a,b,c){if(Xb(b,c))return c.URL;return c.referrer},zd=function(a,b,c){if(yd(a,b,c)!=c.URL)return c.domain;return""},
yd=function(a,b,c){var d=cd(K()).getAttribute("google_page_url");if(d)return d;return xd(a,b,c)},Ad=function(a,b,c,d){U(a,"url",wd(a,yd(a,window,document),window.GA_googleEnv.getParameter("google_preview")));U(a,"ref",document.referrer);U(a,"lmt",(Date.parse(document.lastModified)/1E3).toString());T(a,"dt",b.getTime());if(document.body){b=document.body.scrollHeight;var e=document.body.clientHeight;e&&b&&U(a,"cc",Math.round(e*100/b).toString())}b=f;if(b=Va(b)){U(a,"biw",b.width);U(a,"bih",b.height)}b=
Yb(window);U(a,"ifi",b);b=Xa(window);b!=0&&U(a,"ifk",b.toString());b=dc(c,gd(K(),c));U(a,"adk",b);b=window.GA_googleEnv.getParameter("deb");b!=g&&U(a,"deb",b);b=window.GA_googleEnv.getParameter("haonly");b!=g&&U(a,"haonly",b);b=cd(K());navigator.userAgent.indexOf("MSIE ")>0&&Hc(b,"google_encoding",document.charset,j);e="";if(d)e=Kc(K().a,b,K().B,a.za);else{c=fd(K(),c);if(c==g)c=b;else Ic(c,b);e=c.i()}if(e)a.b+="&"+e},Bd=function(a,b,c){var d=K().r,e=[];for(var h in d)J(d[h])||e.push(v(h)+"="+v(d[h]));
U(a,"cust_params",e.join("&"));if(b._GA_googleCookieHelper){U(a,"cookie",b._GA_googleCookieHelper.w);b._GA_googleCookieHelper.Q&&U(a,"cookie_enabled","1")}(b=zd(a,b,c))&&U(a,"cdm",b)},Cd=function(a){Kb();var b=window;T(a,"ga_vid",b.gaGlobal.vid);T(a,"ga_sid",b.gaGlobal.sid);T(a,"ga_hid",b.gaGlobal.hid);T(a,"ga_fc",b.gaGlobal.from_cookie);U(a,"ga_wpids",b.google_analytics_uacct)},Dd=function(a,b){for(var c in b){var d=b[c];J(d)||T(a,c,d)}},Fd=function(a){var b=[];if(ba(window.GS_googleGetExpIdsForAdSense)==
"function"){var c=window.GS_googleGetExpIdsForAdSense();c&&b.push(c)}(c=Ed(a.f.toString()))&&b.push(c);b.length>0&&U(a,"eid",b.join())};
S.prototype.i=function(a){this.k();Fd(this);var b=new Date;vd(this,a);Bd(this,window,document);window.GA_googleEnv.getParameter("google_preview")!=g&&T(this,"gct",window.GA_googleEnv.getParameter("google_preview"));Cd(this);Ad(this,b,a,this.l);a={};Ua(a);Dd(this,a);T(this,"flash",Sa());this.b=this.b.substring(0,2E3);this.b=this.b.replace(/%\w?$/,"");if(this.da){a=this.g=="iframe"||this.g=="fallback"?"html":"json_html";Gb().registerAdBlockByType(a,this.b,f)}return this.b};
var qc=function(a){return a.u},V=function(a,b){var c=b.getAttribute("id");return c=c.substr(18,c.length-18)},Gd=function(a,b,c,d){a='<ins style="position:relative;width:'+b+"px;height:"+c+'px;border:none;display:block;">'+d+"</ins>";return b='<ins style="position:relative;width:'+b+"px;height:"+c+'px;border:none;display:inline-table;">'+a+"</ins>"},Hd=function(a,b,c,d,e,h){var i="google_ads_iframe_"+b,l=[];b="google_ads_div_"+b;var n="border:0px;left:0;position:absolute;top:0;";l.push("<iframe id=",
i," name=",i,' width="',e,'" height="',h,'" vspace="0" hspace="0" allowtransparency="true" ',"scrolling=",a.m?'"auto"':'"no"',' marginwidth="0" marginheight="0" frameborder="0" ','style="',n,'"',' src="',O(c),'"');d!=g&&l.push(' onload="',d,'"');l.push("></iframe>");c=[];l=l.join("");c.push("<div id=",b,">");c.push(Gd(a,e,h,l));c.push("</div>");a=c.join("");document.write(a)},Id=function(a,b,c){var d=N(a,c),e=d._width_,h=d._height_;d=d._html_;var i=document.createElement("iframe");i.id="google_ads_iframe_"+
c;i.name="google_ads_iframe_"+c;i.width=e;i.height=h;i.vspace=0;i.hspace=0;i.allowTransparency="true";i.scrolling="no";i.marginWidth=0;i.marginHeight=0;i.frameBorder=0;i.style.border=0;b=document.getElementById(b);i.style.position="absolute";i.style.top=0;i.style.left=0;var l=document.createElement("ins");l.style.width=e+"px";l.style.height=h+"px";l.style.border=0;l.style.display="block";l.style.position="relative";var n=document.createElement("ins");n.style.width=e+"px";n.style.height=h+"px";n.style.border=
0;n.style.display="inline-table";n.style.position="relative";l.appendChild(i);n.appendChild(l);b.appendChild(n);if(a.m){i.contentWindow.document.write(O(d));i.scrolling="auto"}else i.contentWindow.document.write(d);i.contentWindow.document.write("<script>document.close();<\/script>");P(K(),c)};function Jd(a,b){Id(L(),a,b)}m("GA_googleCreateDomIframe",Jd);
var Kd=function(){var a=[],b=document.getElementsByTagName("base");if(b)for(var c=0,d=b.length;c<d;++c){var e=b[c],h=e.getAttribute("target");if(h){a.push({baseElement:e,originalTagValue:h});e.removeAttribute("target")}}return a},Ld=function(a){if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b];d.baseElement.setAttribute("target",d.originalTagValue)}},Md=function(a){var b="http://"+ha()+"/pagead/inject_object_div.js";if(parseInt(td(),10)>6)return j;if(a.indexOf(b)<0)return j;return f},Nd=function(a,
b,c){if(a.m)c=O(c);a=Kd();window.frames[b.name].contents=c;b.src=Md(c)?'javascript:document.write(window["contents"]);document.close();':'javascript:window["contents"]';Ld(a)},Od=function(a,b,c){var d=V(a,b);try{var e=b.contentWindow?b.contentWindow.document:b.contentDocument;if(e==g)if(document.implementation&&document.implementation.createDocument)e=document.implementation.createDocument("",d,g);else if(typeof ActiveXObject!="undefined")e=new ActiveXObject("Msxml.DOMDocument");else return j;e.open("text/html",
"replace");a.m?e.write(O(c)):e.write(c);e.close()}catch(h){return j}return f},Pd=function(a,b){var c=V(a,b),d=Q(K(),c);if(!d.X){d.X=f;d=N(a,c);var e=b.parentNode;if(d==g||d._html_==g)e.removeChild(b);else if(d._expandable_&&!(d._is_afc_&&d._is_3pas_))e.innerHTML=d._html_;else d._is_3pas_?Nd(a,b,d._html_):Od(a,b,d._html_);P(K(),c)}},Qd=function(a,b){var c="google_ads_div_"+b;c="<div id="+c+">";var d=N(a,b);if(d!=g){c+=d._html_;c+="\n</div>\n";document.write(c);P(K(),b)}},Rd=function(a,b){var c="google_ads_div_"+
b,d="<div id="+c+">";d+="\n</div>\n";document.write(d);return c},Sd=function(a){if(!a.u)return f;if(Rc(K(),a.u)>0)return f;else if(Tc(K())==0)return j},Td=function(a,b){cc(I,"ga_srt",K().c.length,"_ga_start");if(a.h==g){a.h=b;for(var c in b)J(b[c])||Wc(K(),c)}else for(c in b)if(!J(b[c])){a.h[c]=b[c];Wc(K(),c)}var d=j;for(c in b)if(!J(b[c])){var e=b[c];if(d){e._cookies_=[Tb(window._GA_googleCookieHelper)];d=j}e!=g&&e._cookies_!=g&&window._GA_googleCookieHelper.M(e)}};function Ud(a){Td(L(),a)}
m("GA_googleSetAdContentsBySlot",Ud);function W(a){S.call(this,a);this.u=j;this.f=(new Date).getTime();this.g=a?"sync_sra":"sync"}o(W,S);W.prototype.k=function(){this.b=this.p;U(this,"correlator",this.f.toString());T(this,"output","json_html");T(this,"callback","GA_googleSetAdContentsBySlotForSync");this.l?T(this,"impl","ss"):T(this,"impl","s");Vd(this,K().c);if(!this.l){Wd(this,K().c,this.h);Xd(this,K().c,this.h)}};
var Vd=function(a,b){for(var c=0,d=f,e=0;e<b.length;++e){var h=a.h&&a.h[b[e]];if(h)if(h._is_afc_==undefined){d=j;break}else c=2*c+(h._is_afc_?1:0)}d&&T(a,"prev_afc",c)},Xd=function(a,b,c){if(b&&c){var d=b.length-2;if(d>=0){b=b[d];(c=c[b])&&c._pstok_&&U(a,"pstok",c._pstok_)}}},Wd=function(a,b,c){if(b&&c){for(var d=[],e=[],h=b.length-1,i=0;i<h;i++){var l=b[i];if((l=c[l])&&l._cids_&&l._a2ids_){d.push(l._cids_[0]);e.push(l._a2ids_[0])}else{d.push("");e.push("")}}if(d.length>0){b=d.join(",");e=e.join(",");
U(a,"a2ids",e);U(a,"cids",b)}}},Yd=function(a,b){var c=K().a;c=c[b];if(c!=g)if(!a.t){a.i(c.s);Vc(K(),b);document.write("<script src = '"+a.b+"'><\/script>")}},$d=function(a,b){Td(a,b);if(a.l)if(K().c.length==1){var c=K().c[0];Zd(a,c);return}for(c in b)J(b[c])||Zd(a,c)};function ae(a){$d(L(),a)}m("GA_googleSetAdContentsBySlotForSync",ae);W.prototype.j=function(){Sd(this)};var be=function(a){a.i(g);document.write("<script src = '"+a.b+"'><\/script>");Uc(K())};
W.prototype.n=function(a){K().c.push(a);cc(I,"_ga_start",K().c.length);if(this.l)K().c.length==1?be(this):Zd(this,a);else Yd(this,a)};
var ce=function(a,b,c){if(b.google_js_backfill){a="script";c.write("<"+a+' src="'+La+'"></'+a+">")}},Zd=function(a,b){de(a,window,document,b)},de=function(a,b,c,d){var e=Q(K(),d);if(e!=g){e=N(a,d);Xc(K(),d);if(e==g||e._empty_){ce(a,b,c,d);P(K(),d)}else if(a.K&&!a.m)P(K(),d);else if(e._snippet_&&!e._is_afc_&&!a.m)Qd(a,d);else if(b.navigator.userAgent.indexOf("MSIE ")>0){c="GA_googleSyncAdSlotLoaded(this);";var h="about:blank";if(b=b.GA_googleEnv.getParameter("google_domain_reset_url")){var i=$b(b.match(Zb)[3]||
g);if(i===g||i.indexOf(document.domain)>=0)h=b}Hd(a,d,h,c,e._width_,e._height_)}else{a=Rd(a,d);c.write("<script>GA_googleCreateDomIframe('"+a+"' ,'"+d+"');<\/script>")}}},ee=function(a,b){var c=V(a,b);Q(K(),c);Pd(a,b)};function fe(a){ee(L(),a)}m("GA_googleSyncAdSlotLoaded",fe);function X(a){S.call(this,a);this.f=(new Date).getTime();this.g="async"}o(X,S);
X.prototype.k=function(){this.b=this.p;ge(this);U(this,"correlator",this.f.toString());T(this,"output","json_html");T(this,"callback","GA_googleSetAdContentsBySlot");T(this,"impl","a")};var ge=function(a){a.delay=500;var b=window.GA_googleEnv.getParameter("google_async_delay");if(b!=g)a.delay=1E3*b};X.prototype.j=function(){if(Sd(this))this.t||window.setTimeout("GA_googleReallyFetchAds();",20)};
var he=function(a){if(Rc(K(),a.u)!=0){var b=document.getElementsByTagName("head")[0];if(a.l){var c=document.createElement("script");c.src=a.i(g);b.appendChild(c);Uc(K())}else{var d=K().a;for(var e in d)if(!J(d[e])){c=document.createElement("script");c.src=a.i(e);b.appendChild(c);Vc(K(),e)}}}};function ie(){he(L())}m("GA_googleReallyFetchAds",ie);
X.prototype.n=function(a){var b=Q(K(),a);if(b!=g){K().c.push(a);b="GA_googleAsyncAdSlotLoaded(this);";var c=M(K(),a);Hd(this,a,"about:blank",b,c._width_,c._height_)}};var ke=function(a,b){var c=V(a,b);Q(K(),c);!a.t&&!a.K&&je(a,b)};function le(a){ke(L(),a)}m("GA_googleAsyncAdSlotLoaded",le);var je=function(a,b){var c=V(a,b),d=Q(K(),c);if(a.h==g||a.h[c]==g){if(!(d.aa>30)){window.setTimeout(function(){je(L(),b)},a.delay);d.aa++}}else Pd(a,b)};X.prototype.H=function(){};
function Y(a){S.call(this,a);this.f=(new Date).getTime();this.g="fallback"}o(Y,S);Y.prototype.k=function(){this.b=this.p;U(this,"correlator",this.f.toString());T(this,"output","html");T(this,"impl","fb")};Y.prototype.j=function(){Sd(this)};Y.prototype.z=function(a){if(this.l){this.i(g);a=this.b+"&currentslot="+v(a)}else a=this.i(a);return a};Y.prototype.n=function(a){var b=M(K(),a);if(b!=g){K().c.push(a);if(!this.t){var c=this.z(a);Hd(this,a,c,g,b._width_,b._height_)}}};
function Z(a){S.call(this,a);this.f=(new Date).getTime();this.N=f;this.g="iframe"}o(Z,S);Z.prototype.k=function(){this.b=this.p;U(this,"correlator",this.f.toString());T(this,"output","html");T(this,"impl","ifr")};Z.prototype.j=function(){Sd(this)};Z.prototype.z=function(a){if(this.l){this.i(g);a=this.b+"&currentslot="+v(a)}else a=this.i(a);return a};Z.prototype.n=function(a){var b=M(K(),a);if(b!=g){K().c.push(a);if(!this.t){var c=this.z(a);Hd(this,a,c,g,b._width_,b._height_)}}};
var me=function(){if(Ra()){var a=td();return a<=5}else if(w("firefox")){var b=navigator.userAgent.indexOf("Firefox")+8;a=parseInt(navigator.userAgent.charAt(b),10);b=navigator.userAgent.slice(b);return a<1}else if(w("safari")){b=navigator.userAgent.indexOf("Safari")+7;b=navigator.userAgent.slice(b);a=parseInt(b,10);return a<412}else if(window.opera!=g){b=navigator.userAgent.indexOf("Opera")+6;b=navigator.userAgent.slice(b);a=parseInt(b,10);return a<9}else if(!Ra()&&!w("safari")&&w("mozilla")){b=navigator.userAgent.indexOf("Netscape")+
9;b=navigator.userAgent.slice(b);a=parseInt(b,10);return a<7}else return f},ne=function(){if(Ra()){var a=td();return a>5}else if(w("firefox")){a=navigator.userAgent.indexOf("Firefox")+8;var b=parseInt(navigator.userAgent.charAt(a),10);navigator.userAgent.slice(a);return b>1}return j},oe=function(){if(me())return"fallback";else if(window.google_delayFetch&&ne())return"async";return"sync"},hc=function(a){var b=g;if(typeof a!="undefined"&&a!=g)b=a;else{b=window.GA_googleEnv.getParameter("google_ad_impl");
if(b==g)b=oe()}switch(b){case "async":return new X(j);case "sync":return new W(j);case "sync_sra":return new W(f);case "fallback":return new Y(j);case "iframe":return new Z(j);default:return new Y(j)}},$;function K(){$||($=new wc(Hb));return $}function vc(a){delete $;$=a}var pe;function L(){pe||(pe=g);return pe}function gc(a){delete pe;pe=a}if(typeof window.GA_googleEnv=="undefined")window.GA_googleEnv=new Bc;if(typeof window.GA_googleAdCapture=="undefined")window.GA_googleAdCapture=new Dc;
if(window._GA_googleCookieHelper==g)window._GA_googleCookieHelper=new H(g);function Ed(a){var b=Gb(),c=b.getEid();if(c==""){if(c=qe(window)){var d=b.getOsdMode();if(c=="36815006"||c=="36813008"){b.setValidOutputTypes(["html","json_html"]);d=c=="36815006"?1:0}b.setupOsd(d,c,a);(a=L())&&pd(a)}}else if(c!="36815006"&&c!="36815005"&&c!="36813008"&&c!="36813007")c="";return c}
function qe(a){if((a.google_unique_id||0)!=0)return"";a=Ta(["36815005","36815006"],cb);if(a=="")a=Ta(["36813007","36813008"],db);return a}I.tick("js_parse","js_load");I.tick("jl");})()
