package com.htxx.demo1.model;



/**
 * AbstractUsers generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractUsers  implements java.io.Serializable {


    // Fields    

     private String id;
     private String username;
     private String password;


    // Constructors

    /** default constructor */
    public AbstractUsers() {
    }

    
    /** full constructor */
    public AbstractUsers(String username, String password) {
        this.username = username;
        this.password = password;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
   








}