package com.htxx.demo1.model;
// Generated by MyEclipse - Hibernate Tools



/**
 * Users generated by MyEclipse - Hibernate Tools
 */
public class Users extends AbstractUsers implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public Users() {
    }

    
    /** full constructor */
    public Users(String username, String password) {
        super(username, password);        
    }
   
}
